export const tags: Tag[] = [
  { name: "All", value: "all" },
  { name: "Lucid", value: "lucid" },
  { name: "Nightmare", value: "nightmare" },
  { name: "Fantastic", value: "fantastic" },
  { name: "Recurrent", value: "recurrent" },
  { name: "Daydream", value: "daydream" },
  { name: "Dystopian", value: "dystopian" },
  { name: "False Awakening", value: "false-awakening" },
  { name: "Prophetic", value: "prophetic" },
  { name: "Healing", value: "healing" },
  { name: "Epic", value: "epic" },
  { name: "Signal", value: "signal" },
  { name: "Mutual", value: "mutual" },
  { name: "Progressive", value: "progressive" },
  { name: "Past Life", value: "past-life" },
  { name: "Tragic", value: "tragic" },
  { name: "Dramatic", value: "dramatic" },
  { name: "Night Terrors", value: "night-terrors" },
  { name: "Other", value: "other" },
];
